### ISSUE TITLE
Pass repo to handlers?

### ISSUE THREAD

**Issue by LostKobrakai** [CargoSense/fable#4]
I'm just trying out the changes in #3 on an upcoming project of mine and it kinda seems consistent to also pass the repo to handlers. I cannot see any reason why any code running in a transaction should be forces to hardcode the repo, just so it doesn't work properly once executed on a different repo. 

```elixir
  def handlers do
    %{
      Product.Created => &product_created/2
    }
  end

  def create_product(attrs) do
    Lending.Events.emit(%Product{}, fn _product, _repo, _ ->
      %Product.Created{attrs: attrs}
    end)
    |> Lending.Repo.transaction()
  end

  defp product_created(%Product{} = product, %Product.Created{attrs: attrs}) do
    product
    |> Product.create_changeset(attrs)
    |> Lending.Repo.insert()
    # vs
    |> repo.insert()
  end
```

**Comment by benwilson512** [comment]
Yeah that's a fair point, what would the answer to that look like, a third arg on the RHS with the repo?

**Comment by LostKobrakai** [comment]
Yep. I wasn't really sure if first or third, but I guess third is the better place for it to be.

**Comment by LostKobrakai** [comment]
https://github.com/elixir-ecto/ecto/commit/2b83a9441cdbef9e3bacf17c490fec6da90002ad

If we can limit ecto to `>3.2.0` `Events.emit` does no longer need the config to provide the repo, but it's passed by ecto via the `Repo.transaction(fn repo -> … end)`.

**Comment by benwilson512** [comment]
I'm perfectly happy to limit to top of the line ecto. We still need the config to get the handlers though right?

**Comment by LostKobrakai** [comment]
There's `repo`, `event_schema` and `router` currently in the config. The `repo` is provided by what you call after `MyApp.Events.emit`, so I'd like to make that one an explicit param on the API. The others feel fine as compile time provided settings.

**Comment by LostKobrakai** [comment]
Implemented with https://github.com/CargoSense/fable/pull/15
