### ISSUE TITLE
Open requirement on postgrex

### ISSUE THREAD

**Issue by LostKobrakai** [CargoSense/fable#5]
The most current version of postgrex is 0.15. Fable locks to 0.14. I'm not sure how strict fable should be in terms of postgrex. In the end all it cares about should be that usage through ecto works.

**Comment by benwilson512** [comment]
@LostKobrakai Fable uses Postgrex directly when handling the advisory locks. 0.15 may be fine as long as the API around that didn't break. I haven't tested that yet though.

**Comment by benwilson512** [comment]
Tested on 0.15, works fine, relaxed in master.
