### ISSUE TITLE
Noop handler

### ISSUE THREAD

**Issue by LostKobrakai** [CargoSense/fable#6]
Do you think it makes sense to add `Fable.Router.noop/2`, so events could in theory be stored without a handler adding changes to the database afterwards? This would be useful when you just want the event to be stored and e.g. all other sideeffects should happen by process managers. It's probably not a primary usecase for fable, but it would allow for a more pure event sourcing approach if needed.

**Comment by benwilson512** [comment]
Ah so, the handlers spec is roughly
```
@type handler (event, agg) -> agg
@type handlers %{event_module => handler | [handler]}
```
so you can just have `SomeEvent => []` which seems reasonably clear to me.

**Comment by LostKobrakai** [comment]
I didn't know it could be a list. Might need to update a few typespecs of my PR then, but for this it should work out just fine.
